add volunteer Saurav-Pant
codewithvoid/AskDevs pull request #118
Opened 2022-12-12 04:19 UTC by Saurav-Pant

2022-12-12 10:43 UTC, codewithvoid requested changes

2022-12-12 10:43 UTC, codewithvoid commented on data/users/Saurav-Pant.json
> +    "bio": "FrontEnd Developer",
fix casing. `Frontend Developer`

2022-12-12 10:43 UTC, codewithvoid commented on data/users/Saurav-Pant.json
> +        "topics": ["reactjs", "css", "javascript"]
can you mention javascript in separate programming and removing it from here. E.g

```json
{
 "slug" : "programming",
"topics": ["JavaScript"]
}
```

2022-12-12 10:43 UTC, codewithvoid commented on data/users/Saurav-Pant.json
> +    "image": "https://avatars.githubusercontent.com/u/103263909?s=96&v=4",
use simpler url https://avatars.githubusercontent.com/u/103263909?v=4

2022-12-12 19:34 UTC, codewithvoid commented on data/users/Saurav-Pant.json
> +        "slug": "web-development",
@Saurav-Pant change this to programming

2022-12-13 03:21 UTC, Saurav-Pant commented on data/users/Saurav-Pant.json
> +        "slug": "web-development",
@codewithvoid  can you plz tell me Why do I write programming here, is javascript not in web-development categories??

2022-12-15 09:09 UTC, codewithvoid commented on data/users/Saurav-Pant.json
> +        "slug": "web-development",
Thank you!

2022-12-15 09:09 UTC, codewithvoid approved these changes

2022-12-15 09:09 UTC, merged