chore: add volunteer NilsJacobsen
codewithvoid/AskDevs pull request #160
Opened 2022-12-27 11:16 UTC by NilsJacobsen

Hey folks, awesome idea. I'm in. 🚀

2022-12-28 10:35 UTC, codewithvoid commented
Thanks for volunteering @NilsJacobsen. Added some comments PTAL.

2022-12-28 10:35 UTC, codewithvoid requested changes

2022-12-28 10:35 UTC, codewithvoid commented on data/users/NilsJacobsen.json
> +  "image": "https://pbs.twimg.com/profile_images/1491468272226779145/P4zfulvL_400x400.jpg",
use github image url instead? https://avatars.githubusercontent.com/u/58360188?v=4

2022-12-28 10:35 UTC, codewithvoid commented on data/users/NilsJacobsen.json
> +  "bio": "Frontend Dev and Interaction Designer",
Pick 1 title here. Preferably Frontend Dev as we don't have designer related topics atm.

2022-12-28 10:35 UTC, codewithvoid commented on data/users/NilsJacobsen.json
> +      "slug": "interaction-design",
Same as above. Categories are predefined [here](https://github.com/codewithvoid/AskDevs/blob/main/public/categories.json)

2022-12-28 10:35 UTC, codewithvoid commented on data/users/NilsJacobsen.json
> +      "topics": ["react", "nextjs", "recoil", "tailwind"]
keep topics to max 2-3

2022-12-28 19:08 UTC, NilsJacobsen commented
@codewithvoid I applied your change requests.

2022-12-29 01:23 UTC, codewithvoid approved these changes

2022-12-29 01:23 UTC, codewithvoid commented
Perfect. Welcome Nils!

2022-12-29 01:24 UTC, merged