chore: add volunteer samyabrata-maji
codewithvoid/AskDevs pull request #173
Opened 2023-01-08 12:22 UTC by samyabrata-maji

2023-01-08 15:18 UTC, codewithvoid requested changes
Thanks for volunteering @samyabrata-maji. Left few comments.

2023-01-08 15:18 UTC, codewithvoid commented on data/users/samyabrata-maji.json
> +            "slug": "programming | web-development",
looking at the topics..just programming is fine
```json
"slug": "programming"
```

2023-01-08 15:18 UTC, codewithvoid commented on data/users/samyabrata-maji.json
> +    "bio": "Frontend Engineer | Designer",
You can just mention one title for clarity. Frontend engineer/developer preferably.

2023-01-08 16:40 UTC, samyabrata-maji commented on data/users/samyabrata-maji.json
> +            "slug": "programming | web-development",
I'll go with web-development

2023-01-08 16:42 UTC, samyabrata-maji commented on data/users/samyabrata-maji.json
> +    "bio": "Frontend Engineer | Designer",
ok I'll implement the changes

2023-01-09 15:23 UTC, codewithvoid commented on data/users/samyabrata-maji.json
> +            "topics": [
limit these to max 2-3

2023-01-09 15:24 UTC, codewithvoid commented on data/users/samyabrata-maji.json
> +            "slug": "web-development",
i would suggest change this to programming as topics contain programming languages.

you can add separate entry for web development mentioning web frameworks and technologies you are proficient (keep them max 2-3 too)

2023-01-09 15:38 UTC, samyabrata-maji commented on data/users/samyabrata-maji.json
> +            "slug": "web-development",
ok I'll  add `programming` slug then

2023-01-09 15:38 UTC, samyabrata-maji commented on data/users/samyabrata-maji.json
> +            "topics": [
sure

2023-01-09 15:46 UTC, codewithvoid approved these changes
Thanks for making quick changes. Welcome!

2023-01-09 15:46 UTC, merged