chore: add volunteer bitethecode
codewithvoid/AskDevs pull request #180
Opened 2023-01-10 22:11 UTC by bitethecode

Thanks in advance..!

2023-01-11 08:01 UTC, codewithvoid requested changes
Thanks for volunteering @bitethecode :). Left few comments. Please check.

2023-01-11 16:25 UTC, bitethecode commented on data/users/bitethecode.json
> +  "bio": "Software Engineer",
Oh thanks!

2023-01-11 16:30 UTC, bitethecode commented
I updated it following your suggestion. Let me know if there is anything I should fix..!

2023-01-11 16:33 UTC, codewithvoid commented on data/users/bitethecode.json
> +      "topics": ["algorithms", "system design", "python", "go"]
move system design to software development

2023-01-11 16:35 UTC, bitethecode commented on data/users/bitethecode.json
> +      "topics": ["algorithms", "system design", "python", "go"]
can I also say `backend` under software-development? I know it's vague but it's my main focus

2023-01-11 16:38 UTC, codewithvoid commented on data/users/bitethecode.json
> +      "topics": ["algorithms", "system design", "python", "go"]
We are covering backend technologies in web development category. Hence it would be redundant.

You can mention backend web technologies and frameworks in `web-development` slug

2023-01-12 04:41 UTC, codewithvoid approved these changes

2023-01-12 04:41 UTC, codewithvoid commented
Perfect. Welcome @bitethecode to the community!

2023-01-12 04:41 UTC, merged