chore: add volunteer chozeur
codewithvoid/AskDevs pull request #182
Opened 2023-01-11 12:31 UTC by chozeur

Hi all, glad to take part in this project !

2023-01-12 04:43 UTC, codewithvoid requested changes
Thanks for volunteering @chozeur. Added a somment. PTAL.

2023-01-12 04:43 UTC, codewithvoid commented on data/users/chozeur.json
> +	"bio": "Willing dev, student at 42 Paris",
Use title here. Like Sofware Developer / Software Engineer.

That will be useful for developers seeking help.

2023-01-12 11:12 UTC, chozeur commented on data/users/chozeur.json
> +	"bio": "Willing dev, student at 42 Paris",
My bad, I've made the changes. Thanks.

2023-01-12 11:29 UTC, codewithvoid requested changes

2023-01-12 11:29 UTC, codewithvoid commented on data/users/chozeur.json
> +	"bio": "Sofware Developer",
fix typo :)

2023-01-12 13:25 UTC, chozeur commented on data/users/chozeur.json
> +	"bio": "Sofware Developer",
my bad

2023-02-18 18:03 UTC, codewithvoid approved these changes
Thanks for making the changes. Welcome!

You can join the community [here](https://discord.gg/Tn9E5pn5)

2023-02-18 18:03 UTC, merged