Create hrshtmlng.json
codewithvoid/AskDevs pull request #186
Opened 2023-01-12 21:24 UTC by hrshtmlng

2023-01-14 03:46 UTC, codewithvoid requested changes
Thanks for volunteering @hrshtmlng. Left some comments.

2023-01-14 03:46 UTC, codewithvoid commented on data/users/hrshtmlng.json
> +  "bio": "Im bridging the gap between design and code as a Frontend Developer",
just mention the title here -> `Frontend Developer`

2023-01-14 03:46 UTC, codewithvoid commented on data/users/hrshtmlng.json
> +      "slug": "programming | software-development | web-development ",
move langauges to programming category and can strip version from technologies. updated in below example
```json
[
  {
    "slug": "web-development",
    "topics": [
      "HTML",
      "CSS"
    ]
  },
  {
    "slug": "programming",
    "topics": [
      "JavaScript",
      "Python"
    ]
  }
]
```

2023-01-14 03:46 UTC, codewithvoid commented on data/users/hrshtmlng.json
> +    "twitter": "https://twitter.com/hrshtmlng"
just twitter handle here
```json
"twitter": "hrshtmlng"
```

2023-01-14 10:55 UTC, hrshtmlng commented
Done check it out again

2023-01-14 14:56 UTC, codewithvoid commented on data/users/hrshtmlng.json
> +      "slug": "programming | software-development | web-development ",
Can you update this too. One array entry per category.

2023-01-17 18:03 UTC, codewithvoid commented
@hrshtmlng can you please make the suggested changes. Thanks!

2023-01-18 06:38 UTC, codewithvoid requested changes

2023-01-18 06:38 UTC, codewithvoid commented on data/users/hrshtmlng.json
> +    [
remove nested array..just one `[` is required

2023-01-18 06:38 UTC, codewithvoid commented on data/users/hrshtmlng.json
> +    "twitter": "https://twitter.com/hrshtmlng"
resolve as per the comment

2023-01-18 06:38 UTC, codewithvoid commented on data/users/hrshtmlng.json
> +  "image": "https://twitter.com/hrshtmlng/photo",
this twitter photo url won't render..use github one instead 
https://avatars.githubusercontent.com/u/101478591?v=4

2023-02-15 21:33 UTC, codewithvoid approved these changes

2023-02-15 21:34 UTC, codewithvoid commented
Thanks for making the changes. Welcome!

2023-02-15 21:34 UTC, merged