chore: add volunteer OkelloSam21
codewithvoid/AskDevs pull request #192
Opened 2023-01-18 15:42 UTC by OkelloSam21

2023-01-18 15:52 UTC, OkelloSam21 commented
Add OkelloSam files

2023-01-20 17:27 UTC, codewithvoid commented on data/users/OkelloSam21.json
> +      "slug": "programming ",
remove extra space in the end
```json
"slug": "programming"
```

2023-01-20 17:28 UTC, codewithvoid commented on data/users/OkelloSam21.json
> +      "topics": ["Java,Javascript,kotlin"]
Separate array elements for topics
```json
 "topics": ["Java", "Javascript", "Kotlin"]
```

2023-01-20 17:29 UTC, codewithvoid commented on data/users/OkelloSam21.json
> +   {
lowercase slug and separate array elements here too

```json
   {
       "slug": "web-development",
       "topics":["HTML5", "CSS", "JavaScript"]         
    }
```

2023-01-23 06:43 UTC, OkelloSam21 reviewed
done

2023-01-23 06:43 UTC, OkelloSam21 commented on data/users/OkelloSam21.json
> +   {
I've corrected this

2023-02-01 07:39 UTC, codewithvoid requested changes

2023-02-01 07:49 UTC, OkelloSam21 commented on data/users/OkelloSam21.json
> +  "image": "https://https://avatars.githubusercontent.com/u/115361239?s",
I have fixed the url

2023-02-01 07:50 UTC, codewithvoid commented on data/users/OkelloSam21.json
> +   {
Can you resolve this too?

2023-02-01 07:51 UTC, codewithvoid commented on data/users/OkelloSam21.json
> +      "slug": "programming ",
This one is pending.

2023-02-01 07:55 UTC, OkelloSam21 commented on data/users/OkelloSam21.json
> +   {
Ive corrected the url and Ive removed javascript.

2023-02-01 08:19 UTC, OkelloSam21 reviewed
done

2023-02-01 08:19 UTC, OkelloSam21 commented on data/users/OkelloSam21.json
> +      "slug": "programming ",
done but let me check if my json file is valid firts

2023-02-01 08:19 UTC, OkelloSam21 commented on data/users/OkelloSam21.json
> +      "slug": "programming ",
Done checking the file and its valid.

2023-02-01 08:20 UTC, OkelloSam21 commented
I think by now my json file is okay

2023-02-02 16:49 UTC, codewithvoid approved these changes
Thanks @OkelloSam21 for making the changes. Welcome!

2023-02-02 16:49 UTC, merged