chore: add volunteer Harsh971
codewithvoid/AskDevs pull request #194
Opened 2023-01-20 07:44 UTC by Harsh971

2023-01-20 12:52 UTC, accodes21 reviewed
Everything looks good, but can you restrict topics to less than 4.

2023-01-20 12:55 UTC, Harsh971 commented
in bio part ?

2023-01-20 12:56 UTC, Harsh971 commented
> Everything looks good, but can you restrict topics to less than 4.

In bio part ?

2023-01-20 13:00 UTC, Harsh971 commented
> Everything looks good, but can you restrict topics to less than 4.

I have made changes 🤝

2023-01-20 17:24 UTC, codewithvoid requested changes
Thanks for volunteering @Harsh971. Please check feedback comments.

2023-01-20 17:24 UTC, codewithvoid commented on data/users/Harsh.json
> +  "bio": "MERN Stack, DSA",
Can you use title here - Like 'Web Developer'

2023-01-20 17:24 UTC, codewithvoid commented on data/users/Harsh.json
> +      "slug": "DSA and Programming",
use programming slug
```json
"slug": "programming"
```

2023-01-21 10:30 UTC, Harsh971 commented
Changes applied 👍🏻

2023-01-21 23:23 UTC, codewithvoid requested changes

2023-01-21 23:23 UTC, codewithvoid commented on data/users/Harsh971.json
> +      "slug": "Web Development",
use slug from [categories](https://github.com/codewithvoid/AskDevs/blob/main/public/categories.json) file

here

```json
"slug": "web-development"
```

2023-01-21 23:23 UTC, codewithvoid commented on data/users/Harsh971.json
> +      "slug": "Programming",
```json
"slug": "programming"
```

2023-01-21 23:23 UTC, codewithvoid commented on data/users/Harsh971.json
> +      "topics": ["C", "Cpp", "Java"]
nit: use `c++`

2023-01-21 23:23 UTC, codewithvoid commented on data/users/Harsh971.json
> +      "topics": ["JS", "ReactJs", "MySQL"]
Move mysql to `database-development` category

2023-01-22 08:02 UTC, Harsh971 commented
Changes Applied...

2023-01-22 18:39 UTC, codewithvoid approved these changes
Thanks for making the changes. Welcome to the community :)

2023-01-22 18:39 UTC, merged