chore: add volunteer pranshuj73
codewithvoid/AskDevs pull request #195
Opened 2023-01-22 05:18 UTC by pranshuj73

2023-01-23 16:40 UTC, codewithvoid requested changes
Thanks for volunteering @pranshuj73. Added a small comment.

2023-01-23 16:40 UTC, codewithvoid commented on data/users/pranshuj73.json
> +      "topics": ["Python", "JavaScript", "Web3"]
Add solidity here instead of web3?

2023-01-25 14:34 UTC, pranshuj73 commented on data/users/pranshuj73.json
> +      "topics": ["Python", "JavaScript", "Web3"]
Changed web3 to solidity :]

2023-01-25 19:57 UTC, codewithvoid commented
Thanks @pranshuj73 for making the changes. Welcome :)

2023-01-25 19:57 UTC, codewithvoid approved these changes

2023-01-25 19:57 UTC, merged