added footer
codewithvoid/AskDevs pull request #197
Opened 2023-01-23 05:57 UTC by Anuragwagh

2023-01-24 07:45 UTC, codewithvoid requested changes
Thanks a ton for making the changes. Left few comments.

2023-01-24 07:45 UTC, codewithvoid commented on data/users/AnuragWagh.json
> +    "name": "Anurag Wagh",
revert this file: send in a separate change like [this](https://github.com/codewithvoid/AskDevs/pull/196)

2023-01-24 07:45 UTC, codewithvoid commented on public/categories.json
> +    "slug": "AI-ML"
you can use `data-science` slug instead of adding this

2023-01-24 07:45 UTC, codewithvoid commented on src/components/Footer.js
> +            <a class="title-font font-medium text-white tracking-widest text-xlm mb-3" href='https://twitter.com/codewithvoid'>twitter</a>
capitalize Twitter text here

2023-01-24 07:45 UTC, codewithvoid commented on yarn.lock
> +# yarn lockfile v1
can you revert this..we support package-lock.json for the project

2023-01-27 15:29 UTC, codewithvoid commented
@Anuragwagh Let me know if you are facing any issue while making requested changes.

2023-01-27 19:15 UTC, Anuragwagh commented
I'm not sure what exactly has to do with package json file it will great if you provide guidance

2023-01-27 20:08 UTC, closed without merging