chore: add volunteer ArkaPrabhaChowdhury
codewithvoid/AskDevs pull request #204
Opened 2023-01-28 18:39 UTC by ArkaPrabhaChowdhury

2023-01-29 08:05 UTC, codewithvoid requested changes
Thank you @ArkaPrabhaChowdhury for volunteering. Left few comments. PTAL.

2023-01-29 08:05 UTC, codewithvoid commented on data/users/ArkaPrabhaChowdhury.json
> +      "topics": ["ReactJS","Tailwind","Javascript"]
Move javascript to separate `programming` category like [here](https://github.com/codewithvoid/AskDevs/blob/main/data/users/codewithvoid.json)

2023-01-29 08:05 UTC, codewithvoid commented on data/users/ArkaPrabhaChowdhury.json
> +  "bio": "Front end developer | Intern at german startup",
Just pick 1 title. Preferably, `Frontend Developer`
```json
"bio": "Frontend Developer"
```

2023-01-29 08:05 UTC, codewithvoid commented on data/users/ArkaPrabhaChowdhury.json
> +  "image": "https://www.linkpicture.com/q/me_6.jpg",
optional: use github image url https://avatars.githubusercontent.com/u/92904175?v=4.

This loads well across geographic regions

2023-01-31 12:07 UTC, ArkaPrabhaChowdhury commented
Hey, @codewithvoid Could you please check it now?

2023-01-31 13:40 UTC, codewithvoid requested changes

2023-01-31 13:40 UTC, codewithvoid commented on data/users/ArkaPrabhaChowdhury.json
> +      "topics": ["ReactJS","Tailwind","Javascript"]
Remove javascript from here

2023-01-31 13:40 UTC, codewithvoid commented on data/users/ArkaPrabhaChowdhury.json
> +      "topics": ["ReactJS","Tailwind","Javascript"]
nit: TailwindCSS?

2023-01-31 13:40 UTC, codewithvoid commented on data/users/ArkaPrabhaChowdhury.json
> +  "bio": "Front end developer",
`Frontend Developer`

2023-01-31 14:29 UTC, ArkaPrabhaChowdhury commented
@codewithvoid My apologies, PTAL now.

2023-02-01 07:36 UTC, codewithvoid approved these changes
Thanks for making the changes @ArkaPrabhaChowdhury. Welcome!

2023-02-01 07:36 UTC, merged