Create Ugyenwangdi.json
codewithvoid/AskDevs pull request #205
Opened 2023-01-29 05:43 UTC by Ugyenwangdi

2023-01-29 08:01 UTC, codewithvoid requested changes
Thanks @Ugyenwangdi for volunteering. Added few comments.

2023-01-29 08:01 UTC, codewithvoid commented on data/users/Ugyenwangdi.json
> +  "bio": "Full Stack developer | API developer ",
you can just mention Full Stack Developer..that covers the latter

2023-01-29 08:01 UTC, codewithvoid commented on data/users/Ugyenwangdi.json
> +      "topics": ["Django", "API", "JavaScript"]
move javascript to separate entry `programming` like [here](https://github.com/codewithvoid/AskDevs/blob/main/data/users/codewithvoid.json)

2023-01-31 13:50 UTC, codewithvoid approved these changes
Thanks @Ugyenwangdi for making the changes. Welcome!

2023-01-31 13:50 UTC, merged

2023-02-01 06:35 UTC, Ugyenwangdi commented
> Thanks @Ugyenwangdi for making the changes. Welcome!

Thanks for helping out!