chore: add volunteer vasujhawar2001
codewithvoid/AskDevs pull request #210
Opened 2023-02-01 18:02 UTC by vasujhawar2001

None.
Let me know if any changes, and love this project.

2023-02-02 16:47 UTC, codewithvoid requested changes
Thanks @vasujhawar2001 for volunteering. Added some comments.

2023-02-02 16:47 UTC, codewithvoid commented on data/users/vasujhawar2001.json
> +  "image": "https://pbs.twimg.com/profile_images/1485515284526297090/kL9h_WcB_400x400.jpg",
can you use github image url here

2023-02-02 16:47 UTC, codewithvoid commented on data/users/vasujhawar2001.json
> +      "topics": ["javascript", "pyhton", "TypeScript", "Java"]
- use `programming` slug
- limit topics to max 2-3
- fix typo in python language

2023-02-02 16:47 UTC, codewithvoid commented on data/users/vasujhawar2001.json
> +      "topics": ["Data Structures", "Algorithms", "Systems Design"]
mention `DSA` in programming topic. mention `System Design` in `software-development` category

2023-02-02 16:47 UTC, codewithvoid commented on data/users/vasujhawar2001.json
> +      "topics": ["react.js", "next.js", "mongoDB"]
mention MongoDB in `database-development` category slug

2023-02-03 17:06 UTC, vasujhawar2001 commented on data/users/vasujhawar2001.json
> +  "image": "https://pbs.twimg.com/profile_images/1485515284526297090/kL9h_WcB_400x400.jpg",
done!

2023-02-04 14:53 UTC, codewithvoid approved these changes
Thanks @vasujhawar2001 for making the changes.

2023-02-04 14:53 UTC, merged