add volunteer anand007s
codewithvoid/AskDevs pull request #211
Opened 2023-02-04 20:00 UTC by anand007s

2023-02-05 17:18 UTC, codewithvoid requested changes
Thanks for volunteering @anand007s. Added some comments.

2023-02-05 17:18 UTC, codewithvoid commented on data/users/anand007s.json
> +    "twitter": "@anand01twt"
@ is not required here

2023-02-05 17:18 UTC, codewithvoid commented on data/users/anand007s.json
> +      "slug": "Web-developer",
slug is specified in snake case
```json
"slug": "web-development"
```

2023-02-05 17:18 UTC, codewithvoid commented on data/users/anand007s.json
> +  "image": "https://twitter.com/anand01twt/photo",
use this image url
```json
"image": "https://pbs.twimg.com/profile_images/1621920209446780929/EqXUbX04_400x400.jpg"
```

2023-02-05 17:18 UTC, codewithvoid commented on data/users/anand007s.json
> +      "topics": ["Linux","Markdonw","Html","Css","Javascript","ReactJs","Java","SpringBoot"]
limit topics to max 2-3

2023-02-05 17:18 UTC, codewithvoid commented on data/users/anand007s.json
> +  "bio": "Developer",
optional: `Web Developer`

2023-02-08 07:40 UTC, anand007s reviewed
Changes done as per above comments.

2023-02-08 07:50 UTC, anand007s commented on data/users/anand007s.json
> +    "twitter": "@anand01twt"
Done

2023-02-08 07:50 UTC, anand007s commented on data/users/anand007s.json
> +      "slug": "Web-developer",
Done

2023-02-08 07:50 UTC, anand007s commented on data/users/anand007s.json
> +  "image": "https://twitter.com/anand01twt/photo",
Done

2023-02-08 07:50 UTC, anand007s commented on data/users/anand007s.json
> +  "bio": "Developer",
Done

2023-02-08 07:52 UTC, anand007s commented
Changes are Done.

2023-02-08 14:12 UTC, codewithvoid approved these changes
Thanks for making the changes. Welcome!

2023-02-08 14:12 UTC, merged