Changed Data structures to DS and Data structures and Algorithms to DSA | Solves issue #218
codewithvoid/AskDevs pull request #220
Opened 2023-02-09 06:24 UTC by ArkaPrabhaChowdhury

I have also made sure that DSA and DS remain capitalized. 
![image](https://user-images.githubusercontent.com/92904175/217734320-75f627d1-0221-4316-93bb-6a625c0873cd.png)

2023-02-09 11:32 UTC, codewithvoid requested changes

2023-02-09 11:32 UTC, codewithvoid commented on data/users/vasujhawar2001.json
> +      "topics": ["Javascript", "DS", "Java"]
@ArkaPrabhaChowdhury let's change all to DSA

2023-02-09 11:32 UTC, codewithvoid commented on src/pages/index.js
> +      if(str=="DSA" || str=="DS"){
let's create a `Set` of topics which will be ignored from title casing and check here if topic string is part of that list.

2023-02-09 11:44 UTC, ArkaPrabhaChowdhury commented
@codewithvoid PTAL.

2023-02-09 12:49 UTC, codewithvoid commented on src/pages/index.js
> +      if(capitalize.has(str)){
nit: `capitalize` -> `capitalizedTopics`

2023-02-09 12:50 UTC, codewithvoid approved these changes

2023-02-10 18:15 UTC, codewithvoid commented on src/pages/index.js
> +      if(capitalize.has(str)){
@ArkaPrabhaChowdhury this is ready to submit. Can you make this change.

2023-02-10 18:18 UTC, ArkaPrabhaChowdhury commented on src/pages/index.js
> +      if(capitalize.has(str)){
@codewithvoid Sure!

2023-02-10 18:21 UTC, ArkaPrabhaChowdhury commented
@codewithvoid PTAL.

2023-02-10 19:39 UTC, merged