Add volunteer AbhijithRajesh
codewithvoid/AskDevs pull request #221
Opened 2023-02-09 17:04 UTC by abhijith-zero

2023-02-10 18:15 UTC, codewithvoid requested changes
Thanks for volunteering @abhijith-zero. Left some comments.

2023-02-10 18:15 UTC, codewithvoid commented on data/users/AbhijithRajesh.json
> +{
Rename filename to `abhijith-zero.json`

2023-02-10 18:15 UTC, codewithvoid commented on data/users/AbhijithRajesh.json
> +      "topics": ["VueJs", "Laravel", "NestJs","react"]
Limit these to max 2-3 topics

2023-02-10 18:15 UTC, codewithvoid commented on data/users/AbhijithRajesh.json
> +      "topics": ["Python", "PHP", "javascript","C"]
Same here. Max 2-3.

2023-02-11 15:29 UTC, abhijith-zero commented on data/users/AbhijithRajesh.json
> +      "topics": ["VueJs", "Laravel", "NestJs","react"]
Done

2023-02-11 15:29 UTC, abhijith-zero commented on data/users/AbhijithRajesh.json
> +      "topics": ["Python", "PHP", "javascript","C"]
Done

2023-02-11 18:03 UTC, codewithvoid approved these changes
Thanks for making the changes. Welcome!

2023-02-11 18:03 UTC, merged