chore: add volunteer Dominic_Frei
codewithvoid/AskDevs pull request #222
Opened 2023-02-10 23:39 UTC by DominicFrei

2023-02-12 15:01 UTC, codewithvoid requested changes
Thanks for volunteering @DominicFrei. Requested some changes.

2023-02-12 15:01 UTC, codewithvoid commented on data/users/Dominic_Frei.json
> +      "slug": "IDEs",
we don't have category for IDEs so will need to drop this :|

2023-02-12 15:01 UTC, codewithvoid commented on data/users/Dominic_Frei.json
> +      "topics": ["backend development", "game development", "database development"]
you can mention more specific topics in the categories file above..these are pretty broad.

2023-02-12 21:20 UTC, DominicFrei commented
@codewithvoid Thank you for the quick review. I've added another commit to address your comments. :)

2023-02-13 17:18 UTC, codewithvoid requested changes

2023-02-13 17:18 UTC, codewithvoid commented on data/users/Dominic_Frei.json
> +  "bio": "Senior Software Engineer @MongoDB",
nit: Can drop @MongoDB

2023-02-13 17:18 UTC, codewithvoid commented on data/users/Dominic_Frei.json
> +      "topics": ["Jetbrains Rider", "Jetbrains PyCharm", "Unity3D"]
remove Jetbrains prefix from the topics.

2023-02-13 17:18 UTC, codewithvoid commented on data/users/Dominic_Frei.json
> +    "twitter": "dominicfrei"
You can mention your discord id too. E.g
```json
"discord": "codewithvoid#8967"
```

2023-02-13 17:18 UTC, codewithvoid commented on data/users/Dominic_Frei.json
> +  "image": "https://pbs.twimg.com/profile_images/1321489002759946240/J2aAULS-_400x400.jpg",
mind using github image url github image url
https://avatars.githubusercontent.com/u/1942012?v=4

It renders well across all regions

2023-02-13 21:35 UTC, codewithvoid commented on data/users/Dominic_Frei.json
> +  "bio": "Senior Software Engineer @MongoDB",
Optional.

Was wondering if its too long for card title. Will create separate issue if that's the case.

2023-02-13 21:36 UTC, codewithvoid approved these changes
Thanks for making the changes. Welcome!

2023-02-13 21:36 UTC, merged

2023-02-14 13:53 UTC, DominicFrei commented
Thank you, @codewithvoid !