Add volunteer rahulpandey70
codewithvoid/AskDevs pull request #239
Opened 2023-02-20 15:43 UTC by rahulpandey70

add volunteer

2023-02-20 22:51 UTC, codewithvoid requested changes
Thanks @rahulpandey70 for volunteering. Change looks great. Added small comments. Please check.

2023-02-20 22:51 UTC, codewithvoid commented on data/users/rahulpandey70.json
> +  "image": "https://avatars.githubusercontent.com/u/34403988?s=400&u=733d087b149c2e488b69a5e41e63aae242b31c69&v=4",
use simpler image url. e.g
```json
"image": "https://avatars.githubusercontent.com/u/34403988?v=4"
```

2023-02-20 22:51 UTC, codewithvoid commented on data/users/rahulpandey70.json
> +      "topics": ["Docker", "Kubernetes", "Aws"]
nit: `AWS`

2023-02-21 02:53 UTC, rahulpandey70 commented on data/users/rahulpandey70.json
> +  "image": "https://avatars.githubusercontent.com/u/34403988?s=400&u=733d087b149c2e488b69a5e41e63aae242b31c69&v=4",
done

2023-02-21 07:21 UTC, codewithvoid approved these changes
Perfect. Welcome!

You can join the community discord [here](https://discord.gg/Tn9E5pn5)

2023-02-21 07:22 UTC, merged