added discord link
codewithvoid/AskDevs pull request #243
Opened 2023-02-25 17:57 UTC by jayk-gupta

added discord link of Askdevs:
https://discord.com/invite/VgFMfMJn

2023-02-26 15:20 UTC, codewithvoid commented
Thanks @jayk-gupta for the PR.

I was thinking of adding link with image in a separate section. Example and code below. Can you please update. Place it after demo section.

## 👋 Join Us On Discord

<a href="https://discord.gg/DFwsFKfgEB"><img src="https://seeklogo.com/images/D/discord-logo-134E148657-seeklogo.com.png" alt="DiscordLogo" width="100" height="100"></a>

## Code
```markdown
## 👋 Join Us On Discord

<a href="[discord.gg/DFwsFKfgEB](https://discord.gg/DFwsFKfgEB)"><img src="https://seeklogo.com/images/D/discord-logo-134E148657-seeklogo.com.png" alt="DiscordLogo" width="100" height="100"></a>
```

2023-02-26 15:22 UTC, codewithvoid requested changes

2023-02-26 15:22 UTC, codewithvoid commented on data/users/jayk-gupta.json
> +  "bio": " Web Dev ",
remove extra spaces
```json
"bio": "Web Dev"
```

2023-02-26 15:22 UTC, codewithvoid commented on data/users/jayk-gupta.json
> +      "topics": ["CSS","javascript"]
Add javascript in programming category. Example.
```json
{
  "slug": "programming",
  "topics": ["JavaScript"]
}
```

2023-02-26 15:22 UTC, codewithvoid commented on README.md
revert this file in this PR

2023-02-26 16:42 UTC, jayk-gupta commented
> Thanks @jayk-gupta for the PR.
> 
> I was thinking of adding link with image in a separate section. Example and code below. Can you please update. Place it after demo section.
> 
> ## 👋 Join Us On Discord
> [<img alt="DiscordLogo" width="100" height="100" src="https://camo.githubusercontent.com/d1f2b3bc758a781be6e5c2547178fd15af6f2427dfc0d719d41fe04b7506b996/68747470733a2f2f7365656b6c6f676f2e636f6d2f696d616765732f442f646973636f72642d6c6f676f2d313334453134383635372d7365656b6c6f676f2e636f6d2e706e67">](https://discord.gg/DFwsFKfgEB)
> 
> ## Code
> ```gfm
> ## 👋 Join Us On Discord
> 
> <a href="[discord.gg/DFwsFKfgEB](https://discord.gg/DFwsFKfgEB)"><img src="https://seeklogo.com/images/D/discord-logo-134E148657-seeklogo.com.png" alt="DiscordLogo" width="100" height="100"></a>
> ```

2023-02-26 16:45 UTC, jayk-gupta commented
Updated the discord task.
I don't know whether the json file was edited or not, I have updated that too.
Thanks for the help!

2023-02-26 18:25 UTC, codewithvoid requested changes

2023-02-26 18:25 UTC, codewithvoid commented on README.md
> +Join our discord server: https://discord.com/invite/VgFMfMJn
remove this line

2023-02-26 18:25 UTC, codewithvoid commented on data/users/jayk-gupta.json
> +      "topics": [""javascript"]
can you make this change in separate branch? It should not be submitted with the discord link change.

2023-02-27 15:25 UTC, codewithvoid commented
@jayk-gupta are you working on the comments? We need discord link change soon.

2023-02-27 19:04 UTC, codewithvoid commented
> > @jayk-gupta are you working on the comments? We need discord link change soon.
> 
> Comments on PRs? What do I need to do exactly? I can work on this.

Yes. The PR comments. I would suggest revert data/users file and send it separately.

2023-02-28 05:21 UTC, jayk-gupta commented
> > > @jayk-gupta are you working on the comments? We need discord link change soon.
> > 
> > 
> > Comments on PRs? What do I need to do exactly? I can work on this.
> 
> Yes. The PR comments. I would suggest revert data/users file and send it separately.

What to send seperately? My PR of adding my info,right?

2023-03-01 18:19 UTC, codewithvoid commented
> What to send seperately? My PR of adding my info,right?
Yes. Just add discord link in this PR. (README file change)

2023-03-02 04:22 UTC, jayk-gupta commented
> > What to send seperately? My PR of adding my info,right?
> > Yes. Just add discord link in this PR. (README file change)

okay

2023-03-07 04:49 UTC, closed without merging