Create ShaikMoAbdullah.json
codewithvoid/AskDevs pull request #246
Opened 2023-03-03 03:01 UTC by ShaikMoAbdullah

chore: add ShaikMoAbdullah profile to AskDevs

2023-03-03 18:09 UTC, codewithvoid requested changes
Thanks @ShaikMoAbdullah for volunteering. Can you please address the comments?

2023-03-03 18:09 UTC, codewithvoid commented on data/users/ShaikMoAbdullah.json
> +  "bio": "JavaScript Developer | Web Dev | React Dev",
pick 1 title. `Web Developer` preferably

2023-03-03 18:09 UTC, codewithvoid commented on data/users/ShaikMoAbdullah.json
> +  "image": "https://drive.google.com/file/d/1r4aHtrJWeIKD4HuKArl4MHQFPjXbbwHR/view?usp=sharing",
can you use github url instead
https://avatars.githubusercontent.com/u/52700318?v=4

2023-03-03 18:09 UTC, codewithvoid commented on data/users/ShaikMoAbdullah.json
> +    {
you can only use 1 slug per category.
```json
[
  {
    "slug": "programming",
    "topics": [
      "JavaScript"
    ]
  },
  {
    "slug": "web-development",
    "topics": [
      "HTML",
      "CSS",
      "ReactJS"
    ]
  }
]
```

2023-03-03 18:09 UTC, codewithvoid commented on data/users/ShaikMoAbdullah.json
> +    "twitter": "ShaikMoAbdullah>"
remove `>`
```json
"twitter": "ShaikMoAbdullah"
```

2023-03-04 13:00 UTC, ShaikMoAbdullah commented on data/users/ShaikMoAbdullah.json
> +  "bio": "JavaScript Developer | Web Dev | React Dev",
Made the changes

2023-03-04 13:02 UTC, ShaikMoAbdullah commented on data/users/ShaikMoAbdullah.json
> +  "image": "https://drive.google.com/file/d/1r4aHtrJWeIKD4HuKArl4MHQFPjXbbwHR/view?usp=sharing",
Made the changes

2023-03-04 13:03 UTC, ShaikMoAbdullah commented on data/users/ShaikMoAbdullah.json
> +    {
Made the changes

2023-03-04 13:03 UTC, ShaikMoAbdullah commented on data/users/ShaikMoAbdullah.json
> +    "twitter": "ShaikMoAbdullah>"
Made the changes

2023-03-04 13:03 UTC, ShaikMoAbdullah commented
Thanks for the feedback

2023-03-04 14:35 UTC, codewithvoid requested changes
Thanks @ShaikMoAbdullah. Can you resolve 2 more changes.

2023-03-04 14:35 UTC, codewithvoid commented on data/users/ShaikMoAbdullah.json
> +      "topics": ["JavaScript", "React", "HTML and CSS"]
you can remove software-development category

2023-03-04 14:35 UTC, codewithvoid commented on data/users/ShaikMoAbdullah.json
> +      "slug": "web-development",
you have already mentioned JavaScript in programming. So just mention others here. Example
```json
  {
    "slug": "web-development",
    "topics": [
      "HTML",
      "CSS",
      "ReactJS"
    ]
  }
```

2023-03-05 17:02 UTC, ShaikMoAbdullah commented on data/users/ShaikMoAbdullah.json
> +      "topics": ["JavaScript", "React", "HTML and CSS"]
Removed

2023-03-05 17:02 UTC, ShaikMoAbdullah commented on data/users/ShaikMoAbdullah.json
> +      "slug": "web-development",
Updated

2023-03-05 18:01 UTC, codewithvoid approved these changes
Thanks for making the changes @ShaikMoAbdullah. Welcome!

2023-03-05 18:02 UTC, merged