chore: add volunteer eskayML
codewithvoid/AskDevs pull request #250
Opened 2023-03-12 12:01 UTC by eskayML

Added myself as a contributor

2023-03-15 21:22 UTC, codewithvoid requested changes
Thanks @eskayML for raising PR. Added small comments. PTAL.

2023-03-15 21:22 UTC, codewithvoid commented on data/users/eskayML.json
> +  "bio": "Python Developer | Data Scientist ",
Better to pick 1. Preferably Data Scientist :)

2023-03-15 21:22 UTC, codewithvoid commented on data/users/eskayML.json
> +      "slug": "programming | machine-learning | data-science",
just `data-science` slug is fine

2023-03-16 06:08 UTC, eskayML commented
Made the changes , thanks

2023-03-16 17:05 UTC, codewithvoid commented
Thanks for making the changes @eskayML. You can join the community [here](https:/discord.gg/DFwsFKfgEB)

2023-03-16 17:06 UTC, codewithvoid approved these changes

2023-03-16 17:06 UTC, merged