add volunteer hartpoli
codewithvoid/AskDevs pull request #264
Opened 2023-03-30 17:13 UTC by hartpoli

added

2023-03-30 18:56 UTC, codewithvoid requested changes
Thank you @hartpoli for volunteering. Added some comments. Please check.

2023-03-30 18:56 UTC, codewithvoid commented on data/users/hartpoli.json
> +    "twitter": ""
add your twitter handle here for people to tweet questions at you

2023-03-30 18:56 UTC, codewithvoid commented on data/users/hartpoli.json
> +      "slug": "programming | software-development | web-development | mobile-development | machine-learning",
per slug entry you need to pick 1 topic.

Also mention specific topics you want to help other developers with. E.g NodeJS, TailwindCSS etc. 
Refer other data files.

2023-03-30 18:56 UTC, codewithvoid commented on data/users/hartpoli.json
> +  "bio": "ML | Web | Android  ",
pick 1 bio. E.g Web Developer.

2023-04-01 01:16 UTC, codewithvoid requested changes

2023-04-01 01:16 UTC, codewithvoid commented on data/users/hartpoli.json
> +      "topics": ["JavaScript", "Python", "C+"]
nit: C++

2023-04-01 01:16 UTC, codewithvoid commented on data/users/hartpoli.json
> +      "slug": "NodeJs",
Update this as below:
```json
"slug": "web-development",
"topics": ["NodeJS", "ExpressJS"]
```

2023-04-01 01:16 UTC, codewithvoid commented on data/users/hartpoli.json
> +    "twitter": "https://twitter.com/yhartpx123"
just username is ok.
```json
"twitter": "yhartpx123"
```

2023-04-03 03:58 UTC, hartpoli commented
anyinfo for update?

2023-04-03 16:59 UTC, codewithvoid requested changes

2023-04-03 16:59 UTC, codewithvoid commented on data/users/hartpoli.json
> +      "slug": "Web Development",
slug doesn't have space and is lowercase
```
      "slug": "web-development",
```

2023-04-03 16:59 UTC, codewithvoid commented on data/users/hartpoli.json
> +  "bio": "Backend Developer ",
remove extra space in the end

2023-04-04 06:49 UTC, codewithvoid approved these changes
Thanks for making the changes. Welcome.

You can join community discord [here]([discord.gg/DFwsFKfgEB](https://t.co/CyAqwr7LNo)).

2023-04-04 06:49 UTC, merged

2023-04-04 06:52 UTC, hartpoli commented
thank u..