New volunteer
codewithvoid/AskDevs pull request #266
Opened 2023-04-07 17:07 UTC by Palakkgoyal

I want to volunteer with you and help other developers and expand my knowledge

2023-04-08 06:53 UTC, codewithvoid requested changes
Thanks for volunteering Palak. 

Added a small comment. Please check.

2023-04-08 06:53 UTC, codewithvoid commented on data/users/Palakkgoyal.json
> +      "topics": ["CSS", "JavaScript", "React", "Tailwind"]
Mention JavaScript in separate `programming` category. 

**Example**
```json
{
  "slug": "programming",
  "topics": ["JavaScript"]
}
```

2023-04-08 17:20 UTC, Palakkgoyal commented
I have done the changes. Please check

2023-04-09 16:33 UTC, codewithvoid approved these changes
Perfect. Welcome to the community. 

[Discord Link](https://discord.gg/DFwsFKfgEB)

2023-04-09 16:33 UTC, merged

2023-04-09 16:38 UTC, Palakkgoyal commented
Thanks a lot Void