New tech Twitter volunteers. ✌️
codewithvoid/AskDevs pull request #267
Opened 2023-04-09 07:37 UTC by JohnSaidi

Adding _JohnSd as a New tech twitter volunteers.

2023-04-09 23:32 UTC, codewithvoid requested changes
Thanks @JohnSaidi for volunteering with AskDevs.

Added couple small comments. PTAL.

2023-04-09 23:32 UTC, codewithvoid commented on data/users/JohnSaidi.json
> +  "name": "<John SD>",
remove < >. e.g
```json
"name": "John Saidi"
```

2023-04-09 23:32 UTC, codewithvoid commented on data/users/JohnSaidi.json
> +      "slug": "programming | software-development",
just mention programming here. e.g
```json
"slug": "programming"
```

2023-04-18 05:17 UTC, JohnSaidi commented on data/users/JohnSaidi.json
> +      "slug": "programming | software-development",
Fixed

2023-04-19 14:44 UTC, merged