add volunteer Pritam1136
codewithvoid/AskDevs pull request #272
Opened 2023-05-27 04:31 UTC by Pritam1136

I have added myself in data/users file.

2023-05-30 14:51 UTC, Pritam1136 commented
Hello @codewithvoid ,

Can you please merge this pull request.

2023-06-12 11:05 UTC, Pritam1136 commented on data/users/pritam1136.json
> +{
when this commit will merge?

2023-06-12 11:10 UTC, codewithvoid requested changes

2023-06-12 11:10 UTC, codewithvoid commented on data/users/pritam1136.json
> +{
Hey apologies for the delay. Added some comments. Please check.

2023-06-12 11:10 UTC, codewithvoid commented on data/users/pritam1136.json
> +    "bio": "C developer | Full-stack development ",
Use 1 title.
```json
"bio": "Full Stack Developer"
```

2023-06-12 11:10 UTC, codewithvoid commented on data/users/pritam1136.json
> +    "image": "https://avatars.githubusercontent.com/u/126561455?s=400&u=dceb8af41ffd4061a38b03eb8d38c4f2e837d8ee&v=4",
Use simpler image url
```json
"image": "https://avatars.githubusercontent.com/u/126561455?v=4"
```

2023-06-12 11:10 UTC, codewithvoid commented on data/users/pritam1136.json
> +        "slug": "web developer",
fix slug
```json
"slug": "web-development"
```

2023-06-12 11:10 UTC, codewithvoid commented on data/users/pritam1136.json
> +        "topics": ["ReactJS", "NodeJS","ExpressJS","TailwindCSS","git & github","Firebase"]
pick max 2-3 items.

2023-06-22 14:20 UTC, closed without merging