Added new Volunteer
codewithvoid/AskDevs pull request #46
Opened 2022-11-26 13:52 UTC by Mayank-KS

2022-11-26 15:06 UTC, codewithvoid commented on data/users/Mayank-KS.json
> +      "slug": "programming | software-development | web-development",
You need to pick one of the category slug. E.g

```
  "categories": [
  {
    "slug": "programming",
    "topics": [
      "JavaScript"
    ]
  },
  {
    "slug": "web-development",
    "topics": [
      "react"
    ]
  }
],
```
 
Sorry for not being super clear.

2022-11-26 15:07 UTC, codewithvoid commented on data/users/Mayank-KS.json
> +  "image": "https://avatars.githubusercontent.com/u/62908116?v=4",
nit: real pic pfp :P

2022-11-26 15:07 UTC, codewithvoid commented
Thanks for volunteering Mayank

2022-11-26 17:44 UTC, RakeshSangem requested changes

2022-11-26 17:44 UTC, RakeshSangem commented on data/users/Mayank-KS.json
> +      "slug": "programming | software-development | web-development",
Hey @Mayank-KS you need to use only one slug.

2022-11-27 07:06 UTC, RakeshSangem commented on data/users/Mayank-KS.json
> +  "image": "https://media-exp1.licdn.com/dms/image/C4D03AQHVR9bNwkTT8Q/profile-displayphoto-shrink_800_800/0/1647273419200?e=2147483647&v=beta&t=9b7AQ2TrUIFchVnNKgVOCVtfAHFE5ofedgq1YDsuP0k",
Link doesn't working. 

Instead use this link `https://pbs.twimg.com/profile_images/1592462470387728384/QanHwY5i_400x400.jpg`

2022-11-27 08:25 UTC, Mayank-KS commented on data/users/Mayank-KS.json
> +  "image": "https://media-exp1.licdn.com/dms/image/C4D03AQHVR9bNwkTT8Q/profile-displayphoto-shrink_800_800/0/1647273419200?e=2147483647&v=beta&t=9b7AQ2TrUIFchVnNKgVOCVtfAHFE5ofedgq1YDsuP0k",
I already solved it with linkedIn pic

2022-11-27 12:40 UTC, RakeshSangem commented on data/users/Mayank-KS.json
> +  "image": "https://media-exp1.licdn.com/dms/image/C4D03AQHVR9bNwkTT8Q/profile-displayphoto-shrink_800_800/0/1647273419200?e=2147483647&v=beta&t=9b7AQ2TrUIFchVnNKgVOCVtfAHFE5ofedgq1YDsuP0k",
> I already solved it with linkedIn pic

Yeah, but it is not working, you can in the deployment preview.

2022-11-27 14:51 UTC, codewithvoid approved these changes

2022-11-27 14:51 UTC, merged