Add new volunteer ibukunoluwanap
codewithvoid/AskDevs pull request #47
Opened 2022-11-26 15:43 UTC by ibukunoluwanap

2022-11-26 17:47 UTC, RakeshSangem requested changes

2022-11-26 17:47 UTC, RakeshSangem commented on data/users/ibukunoluwanap.json
> +  "bio": "💻 • any software development | 🥗 • gets better with food | 🎧 • while listening to beats | 🕹️ • after the game night | creator of flutterme.org",
Hey @ibukunoluwanap , please use short description for example `Frontend developer` `Java developer` `Data Analyst`.

2022-11-26 17:47 UTC, RakeshSangem commented on data/users/ibukunoluwanap.json
> +      "slug": "programming | software-development | web-development | mobile-development | data-science",
You need to use only one slug from `public/categories.json`

2022-11-26 18:43 UTC, ibukunoluwanap commented on data/users/ibukunoluwanap.json
> +      "slug": "programming | software-development | web-development | mobile-development | data-science",
Okay on it

2022-11-26 18:48 UTC, ibukunoluwanap commented
Updated as requested

2022-11-27 04:26 UTC, RakeshSangem commented on data/users/ibukunoluwanap.json
> +  "bio": "A software developer working with Flutter, ReactJS and NodeJS. Creator of flutterme.org",
Please choose short description like `Web Developer` , `Data Analyst` , `Frontend dev`

2022-11-27 08:34 UTC, ibukunoluwanap reviewed
updated bio

2022-11-27 14:52 UTC, codewithvoid commented on data/users/ibukunoluwanap.json
> +  "bio": "Software developer, Frontend developer, Designer",
Prefer having one title here

2022-11-27 14:56 UTC, codewithvoid commented on data/users/ibukunoluwanap.json
> +      "topics": ["Frontend","Flutter", "ReactJS", "NodeJS"]
Frontend is in your title.

Flutter should go in `mobile-development` category

ReactJS and NodeJS in `web-development` category

Final file should be like this

```json
{
  "categories": [
    {
      "slug": "web-development",
      "topics": [
        "ReactJS",
        "NodeJS"
      ]
    },
    {
      "slug": "mobile-development",
      "topics": [
        "Flutter"
      ]
    }
  ]
}
```

2022-11-27 14:56 UTC, codewithvoid commented
Thanks for volunteering @ibukunoluwanap :)

Added some comments

2022-11-27 20:20 UTC, ibukunoluwanap reviewed
updated categories

2022-11-27 20:27 UTC, codewithvoid approved these changes

2022-11-27 20:27 UTC, merged

2022-11-27 20:37 UTC, ibukunoluwanap commented
thanks. check https://github.com/codewithvoid/AskDevs/pull/57/