Add new volunteer Sudha
codewithvoid/AskDevs pull request #48
Opened 2022-11-26 15:49 UTC by surani-hub

2022-11-26 17:50 UTC, RakeshSangem requested changes

2022-11-26 17:50 UTC, RakeshSangem commented on data/users/surani-hub.json
> +      "slug": "programming | software-development",
Hey @surani-hub thanks for volunteering.

You need to choose only one slug. You can find these in `public/categories.json`

2022-11-27 09:46 UTC, surani-hub commented on data/users/surani-hub.json
> +      "slug": "programming | software-development",
Hi @RakeshSangem, I just updated the slug to one field. Could you please check and verify?

2022-11-27 10:00 UTC, codewithshubhi commented on data/users/surani-hub.json
> +      "slug": "programming | software-development",
Hey @surani-hub this should work thanks :)

2022-11-27 14:58 UTC, codewithvoid commented on data/users/surani-hub.json
> +      "topics": ["Java", "Data structures", "Algorithms", "MySQL"]
Keep this to max 2-3.

Also MySQL requires another category `Database Development`

2022-11-28 13:59 UTC, surani-hub commented on data/users/surani-hub.json
> +      "topics": ["Java", "Data structures", "Algorithms", "MySQL"]
Hi @codewithvoid, would you want me to keep the topics to just 3 and remove the remaining?

2022-11-28 14:19 UTC, RakeshSangem commented on data/users/surani-hub.json
> +      "topics": ["Java", "Data structures", "Algorithms", "MySQL"]
> Hi @codewithvoid, would you want me to keep the topics to just 3 and remove the remaining?

yes!

2022-12-01 06:32 UTC, codewithvoid commented
Closing this as it's duplicate of #75

2022-12-01 06:32 UTC, closed without merging