Add new volunteer Satyam Bajpai
codewithvoid/AskDevs pull request #49
Opened 2022-11-26 15:55 UTC by satyam73

2022-11-26 17:53 UTC, RakeshSangem requested changes

2022-11-26 17:53 UTC, RakeshSangem commented on data/users/satyam73.json
> +      "topics": ["javascript", "reactjs", "html", "css", "nodejs", "mongodb"]
minimize topics 2-3

2022-11-27 11:40 UTC, satyam73 commented on data/users/satyam73.json
> +      "topics": ["javascript", "reactjs", "html", "css", "nodejs", "mongodb"]
I have updated topics. Please look into it.

2022-11-27 15:01 UTC, codewithvoid commented on data/users/satyam73.json
> +      "topics": ["frontend", "backend", "javascript"]
@satyam73 would be better to mention frontend and backend technologies that you would like help devs with.

E.g `ReactJS`, `NextJS`, `NodeJS`.

This way devs can ask you more pointed queries.

2022-11-27 15:01 UTC, codewithvoid commented
Thanks for volunteering @satyam73 :)

2022-11-28 09:39 UTC, satyam73 commented on data/users/satyam73.json
> +      "topics": ["frontend", "backend", "javascript"]
I have resolved this. Please take a look.

2022-11-28 09:40 UTC, satyam73 commented
> Thanks for volunteering @satyam73 :)

It's my pleasure to help someone.

2022-11-28 09:53 UTC, merged