Add new volunteer matifanger
codewithvoid/AskDevs pull request #81
Opened 2022-11-30 16:11 UTC by matifanger

2022-11-30 17:26 UTC, accodes21 requested changes
Looks good but try to restrict topics to max 2-3.

2022-11-30 17:39 UTC, codewithvoid commented
Thanks for volunteering @matifanger :)

2022-11-30 17:53 UTC, RakeshSangem requested changes

2022-11-30 17:53 UTC, RakeshSangem commented on data/users/MatiFanger.json
> +      "topics": ["nuxt", "vue", "typescript", "javascript", "python"]
could you limit these topics to 3.

2022-12-01 18:42 UTC, matifanger commented on data/users/MatiFanger.json
> +      "topics": ["nuxt", "vue", "typescript", "javascript", "python"]
Done!

2022-12-02 15:25 UTC, codewithvoid commented on data/users/MatiFanger.json
> +      "topics": ["javascript", "python", "C/C#/C++"]
pick 1 of C/C#/C++

2022-12-15 15:56 UTC, closed without merging